In [1]:
pip install pandas numpy matplotlib seaborn scikit-learn jupyter

Requirement already satisfied: pandas in c:\Users\aashi\miniconda3\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\Users\aashi\miniconda3\Lib\site-packages (2.4.2)
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scikit-learn in c:\Users\aashi\miniconda3\Lib\site-packages (1.8.0)
Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\aashi\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\aashi\miniconda3\Lib\site-packages (from pandas) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from matplotlib) (4.62.1)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in c:\Users\aashi\miniconda3\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\aashi\miniconda3\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from scikit-learn) (3.6.0)
Collecting notebook (from jupyter)
  Downloading notebook-7.6.0-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyter) (7.2.0)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.6.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.5 in c:\Users\aashi\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (9.12.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\aashi\miniconda3\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\Users\aashi\miniconda3\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.5.0)
Requirement already satisfied: executing>=1.2.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure_eval in c:\Users\aashi\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Collecting jupyter-builder>=1.0.2 (from jupyterlab->jupyter)
  Downloading jupyter_builder-1.0.2-py3-none-any.whl.metadata (7.7 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.19.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.20.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: anyio in c:\Users\aashi\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.12.1)
Requirement already satisfied: certifi in c:\Users\aashi\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\Users\aashi\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\Users\aashi\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in c:\Users\aashi\miniconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty!=3.0.4,>=2.0.1 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading pywinpty-3.0.5-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading json5-0.15.0-py3-none-any.whl.metadata (37 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: requests>=2.31 in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.32.5)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading rpds_py-2026.5.1-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pyyaml>=5.3 in c:\Users\aashi\miniconda3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in c:\Users\aashi\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.0)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: beautifulsoup4 in c:\Users\aashi\miniconda3\Lib\site-packages (from nbconvert->jupyter) (4.14.3)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: defusedxml in c:\Users\aashi\miniconda3\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.3.2-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading tinycss2-1.5.1-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\aashi\miniconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.6.1)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: cffi>=1.0.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in c:\Users\aashi\miniconda3\Lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.23)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\aashi\miniconda3\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\aashi\miniconda3\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.15.0)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.3 MB 9.4 MB/s eta 0:00:01
   ---------- ----------------------------- 2.4/9.3 MB 7.0 MB/s eta 0:00:01
   ------------- -------------------------- 3.1/9.3 MB 5.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.3 MB 4.7 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.3 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 5.0/9.3 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 5.5/9.3 MB 3.6 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.3 MB 3.5 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.3 MB 3.2 MB/s eta 0:00:01
   ----------------------------- ---------- 6.8/9.3 MB 3.1 MB/s eta 0:00:01
   ------------------------------- -------- 7.3/9.3 MB 3.1 MB/s eta 0:00:01
   --------------------------------- ------ 7.9/9.3 MB 3.0 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.3 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 8.9/9.3 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 2.9 MB/s  0:00:03
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ---------------------------------- ----- 786.4/914.9 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 914.9/914.9 kB 3.0 MB/s  0:00:00
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.2 MB 3.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.2 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 2.6 MB/s  0:00:00
Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.6.0-py3-none-any.whl (17.1 MB)
   ---------------------------------------- 0.0/17.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.1 MB 5.0 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/17.1 MB 3.3 MB/s eta 0:00:05
   ---- ----------------------------------- 1.8/17.1 MB 2.9 MB/s eta 0:00:06
   ----- ---------------------------------- 2.4/17.1 MB 2.9 MB/s eta 0:00:06
   ------ --------------------------------- 2.9/17.1 MB 2.8 MB/s eta 0:00:06
   ------- -------------------------------- 3.4/17.1 MB 2.8 MB/s eta 0:00:05
   --------- ------------------------------ 3.9/17.1 MB 2.7 MB/s eta 0:00:05
   ----------- ---------------------------- 4.7/17.1 MB 2.7 MB/s eta 0:00:05
   ------------ --------------------------- 5.2/17.1 MB 2.7 MB/s eta 0:00:05
   ------------- -------------------------- 5.8/17.1 MB 2.6 MB/s eta 0:00:05
   -------------- ------------------------- 6.3/17.1 MB 2.6 MB/s eta 0:00:05
   --------------- ------------------------ 6.8/17.1 MB 2.6 MB/s eta 0:00:04
   --------------- ------------------------ 6.8/17.1 MB 2.6 MB/s eta 0:00:04
   ----------------- ---------------------- 7.3/17.1 MB 2.4 MB/s eta 0:00:05
   ------------------ --------------------- 7.9/17.1 MB 2.4 MB/s eta 0:00:04
   -------------------- ------------------- 8.7/17.1 MB 2.5 MB/s eta 0:00:04
   ---------------------- ----------------- 9.4/17.1 MB 2.5 MB/s eta 0:00:04

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("ecommerce_500k.csv")
df.head()

Matplotlib is building the font cache; this may take a moment.

,order_id,customer_id,product_id,order_date,category,sub_category,product_base_price,discount_percentage,final_price,quantity,...,city,loyalty_tier,is_first_purchase,customer_lifetime_value,session_duration_mins,pages_viewed,clicks_to_purchase,is_returned,return_reason,is_cancelled
0,1000001,25795,90,2022-07-31,Clothing,Men,70.41,25,52.81,1,...,Bangalore,Bronze,0,457.77,4.6,35.0,7,0,NaN,0
1,1000002,10860,1917,2023-09-25,Automotive,Car Care,6.02,10,5.42,3,...,Toronto,Bronze,0,1606.42,2.9,8.0,8,0,NaN,0
2,1000003,86820,805,2022-03-26,Books,Textbooks,78.85,20,63.08,2,...,Chicago,Silver,0,252.16,5.5,38.0,8,0,NaN,0
3,1000004,64886,3379,2022-11-03,Books,Non-Fiction,58.42,25,43.82,4,...,Sydney,Bronze,0,645.12,6.1,30.0,9,0,NaN,0
4,1000005,16265,4604,2022-06-30,Clothing,Women,73.38,15,62.37,1,...,Manchester,Bronze,1,1103.24,1.6,38.0,11,0,NaN,0

In [4]:
df.shape

(500000, 30)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   order_id                 500000 non-null  int64
 1   customer_id              500000 non-null  int64
 2   product_id               500000 non-null  int64
 3   order_date               500000 non-null  str
 4   category                 500000 non-null  str
 5   sub_category             500000 non-null  str
 6   product_base_price       500000 non-null  float64
 7   discount_percentage      500000 non-null  int64
 8   final_price              500000 non-null  float64
 9   quantity                 500000 non-null  int64
 10  total_amount             500000 non-null  float64
 11  shipping_cost            484934 non-null  float64
 12  shipping_method          500000 non-null  str
 13  days_to_deliver          484751 non-null  float64
 14  payment_method           500000 non-null  str
 15  rating                   485010 non-null  float64
 16  num_reviews              500000 non-null  int64
 17  customer_age             485072 non-null  float64
 18  customer_gender          500000 non-null  str
 19  country                  500000 non-null  str
 20  city                     500000 non-null  str
 21  loyalty_tier             500000 non-null  str
 22  is_first_purchase        500000 non-null  int64
 23  customer_lifetime_value  484996 non-null  float64
 24  session_duration_mins    485275 non-null  float64
 25  pages_viewed             485186 non-null  float64
 26  clicks_to_purchase       500000 non-null  int64
 27  is_returned              500000 non-null  int64
 28  return_reason            59904 non-null   str
 29  is_cancelled             500000 non-null  int64
dtypes: float64(10), int64(10), str(10)
memory usage: 114.4 MB

In [6]:
df.isnull().sum()

order_id                        0
customer_id                     0
product_id                      0
order_date                      0
category                        0
sub_category                    0
product_base_price              0
discount_percentage             0
final_price                     0
quantity                        0
total_amount                    0
shipping_cost               15066
shipping_method                 0
days_to_deliver             15249
payment_method                  0
rating                      14990
num_reviews                     0
customer_age                14928
customer_gender                 0
country                         0
city                            0
loyalty_tier                    0
is_first_purchase               0
customer_lifetime_value     15004
session_duration_mins       14725
pages_viewed                14814
clicks_to_purchase              0
is_returned                     0
return_reason              440096
is_cancelled                    0
dtype: int64

In [7]:
df.describe()

,order_id,customer_id,product_id,product_base_price,discount_percentage,final_price,quantity,total_amount,shipping_cost,days_to_deliver,rating,num_reviews,customer_age,is_first_purchase,customer_lifetime_value,session_duration_mins,pages_viewed,clicks_to_purchase,is_returned,is_cancelled
count,5.000000e+05,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,484934.000000,484751.000000,485010.000000,500000.000000,485072.000000,500000.000000,484996.000000,485275.000000,485186.000000,500000.000000,500000.000000,500000.000000
mean,1.250000e+06,55007.627196,2503.810058,84.833241,14.599090,72.438608,2.284080,165.605507,34.031570,4.238345,3.796253,27.015930,34.953966,0.278630,850.516871,8.511644,25.054783,9.999486,0.119808,0.061662
std,1.443377e+05,25995.094710,1441.201322,79.984198,12.943309,69.900582,1.739378,237.412198,39.185919,2.398417,0.943732,16.425337,11.132444,0.448325,799.762647,8.035044,14.142187,5.475479,0.324737,0.240541
min,1.000001e+06,10000.000000,1.000000,5.000000,0.000000,2.500000,1.000000,2.500000,0.000000,1.000000,1.000000,0.000000,18.000000,0.000000,50.000000,0.500000,1.000000,1.000000,0.000000,0.000000
25%,1.125001e+06,32490.000000,1259.000000,28.040000,0.000000,23.440000,1.000000,37.710000,4.540000,3.000000,3.500000,15.000000,26.000000,0.000000,280.180000,2.800000,13.000000,5.000000,0.000000,0.000000
50%,1.250000e+06,55056.500000,2503.000000,60.220000,15.000000,50.590000,2.000000,87.700000,24.890000,4.000000,4.000000,24.000000,35.000000,0.000000,604.170000,6.100000,25.000000,10.000000,0.000000,0.000000
75%,1.375000e+06,77510.000000,3752.000000,115.580000,20.000000,98.110000,3.000000,194.070000,44.020000,5.000000,4.500000,36.000000,43.000000,1.000000,1160.032500,11.600000,37.000000,15.000000,0.000000,0.000000
max,1.500000e+06,99998.000000,5000.000000,1148.770000,50.000000,1091.330000,10.000000,6617.300000,200.000000,14.000000,5.000000,166.000000,80.000000,1.000000,11606.040000,121.400000,49.000000,19.000000,1.000000,1.000000